stages:
  - build
  - deploy
variables:
  POSTGRES_USER: $postgres_user
  POSTGRES_PASSWORD: $postgres_password
  POSTGRES_DB: $postgres_db
build:
  stage: build
  image: maven:3.8.3-openjdk-17
  services:
    - name: postgres:latest
  script:
    - echo "Job ID - $CI_JOB_ID"
    - echo "Pipeline ID - $CI_PIPELINE_ID"
    - mvn clean install
deploy:
  stage: deploy
  script:
    - echo "Job ID - $CI_JOB_ID"
    - echo "Pipeline ID - $CI_PIPELINE_ID"
  only:
    - master
    - develop