version: '3.8'
name: javateam38-backend

services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - data:/var/lib/postgresql/data
    networks:
      - socialnet_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G

  db-migrations:
    image: maven:3.8.5-openjdk-17-slim
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./:/project
    command: >
      bash -c "mvn -f /project/db-management/pom.xml liquibase:update"
    depends_on:
      - postgres
    networks:
      - socialnet_network

  frontend:
    container_name: frontend
    image: javapro38/social-net-dock
    restart: unless-stopped
    ports:
      - "8098:80"
    networks:
      - socialnet_network

  user-service:
    container_name: user-svc
    image: javapro38/soc-net-user-svc
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "8081:8081"
    networks:
      - socialnet_network

  communications-service:
    container_name: comm-svc
    image: javapro38/soc-net-comm-svc
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "8082:8082"
    networks:
      - socialnet_network

  gateway-service:
    container_name: gate-svc
    image: javapro38/soc-net-gate-svc
    depends_on:
      - user-service
      - communications-service
    ports:
      - "8080:8080"
    networks:
      - socialnet_network

volumes:
  data:
    driver: local

networks:
  socialnet_network:
    driver: bridge
