version: '3.8'
name: javateam38-backend

services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialnet
    ports:
      - 5433:5432
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - data:/var/lib/postgresql/data
    networks:
      - socialnet_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G

  frontend:
    container_name: frontend
    image: javapro38/social-net-dock
    restart: unless-stopped
    ports:
      - 8098:80
    networks:
      - socialnet_network

  user-service:
    build:
      context: ./social-net-backend/user-service
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 8081:8081
    networks:
      - socialnet_network

  communications-service:
    build:
      context: ./social-net-backend/communications-service
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 8082:8082
    networks:
      - socialnet_network

  gateway-service:
    build:
      context: ./social-net-backend/gateway-service
    depends_on:
      - user-service
      - communications-service
    ports:
      - 8080:8080
    networks:
      - socialnet_network
#    environment:
#      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID=Create-github-client-id
#      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET=Create-github-client-secret
# Use Docker secrets?

volumes:
  data:
    driver: local

networks:
  socialnet_network:
    driver: bridge
