spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - name: RequestRateLimiter
              args:
                burstCapacity: 10
                replenishRate: 2
                redis-rate-limiter:
                  replenishRate: 10
                  burstCapacity: 20
        - id: communications-service
          uri: lb://communications-service
          predicates:
            - Path=/communications-service/**
          filters:
            - name: RequestRateLimiter
              args:
                burstCapacity: 10
                replenishRate: 2
                redis-rate-limiter:
                  replenishRate: 10
                  burstCapacity: 20
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin-service/**
          filters:
            - name: RequestRateLimiter
              args:
                burstCapacity: 10
                replenishRate: 2
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

logging:
  config: classpath:logback-spring.xml