spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    url: ${LIQUIBASE_DATABASE_URL}
    user: ${LIQUIBASE_DATABASE_USERNAME}
    password: ${LIQUIBASE_DATABASE_PASSWORD}
    change-log: classpath:/db/changelog/changelog-master.xml